# Generated by Django 4.0.6 on 2022-09-04 09:48

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCreate',
            fields=[
                ('fieldsmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.fieldsmixin')),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, 'accounts.fieldsmixin', django.views.generic.edit.CreateView),
        ),
    ]
