# Generated by Django 4.0.6 on 2022-09-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fieldsmixin_articlecreate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleCreate',
        ),
        migrations.DeleteModel(
            name='FieldsMixin',
        ),
    ]
